import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'MINcourse',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  )
}
